name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # CMake'yi doğrudan kullanarak yapılandırma ve derleme işlemleri
    - name: Configure project with CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    # Testleri çalıştırıyoruz
    - name: Run tests (Linux)
      run: ./build/InfixToPostfixCalculator
      if: matrix.os == 'ubuntu-latest'

    - name: Run tests (Windows)
      run: build\Debug\InfixToPostfixCalculator.exe
      if: matrix.os == 'windows-latest'

    # Debug ve Release versiyonlarını kuruyoruz
    - name: Install Debug and Release (Linux)
      run: cmake --install build --config Debug --prefix publish_linux
      if: matrix.os == 'ubuntu-latest'

    - name: Install Debug and Release (Windows)
      run: cmake --install build --config Debug --prefix publish_windows
      if: matrix.os == 'windows-latest'

    # GitHub release oluşturma işlemi için INFIX_TOKEN kullanarak yükleme
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.INFIX_TOKEN }}  # INFIX_TOKEN burada kullanılıyor
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false

    # Linux için release dosyasını yükleme
    - name: Upload Release Asset (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish_linux/bin/InfixToPostfixCalculator
        asset_name: InfixToPostfixCalculator_linux
        asset_content_type: application/octet-stream

    # Windows için release dosyasını yükleme
    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish_windows/bin/InfixToPostfixCalculator.exe
        asset_name: InfixToPostfixCalculator_windows.exe
        asset_content_type: application/octet-stream
